import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from "next/font/google";
import ModalProvider from "@/providers/ModalProvider";
import ToastProvider from "@/providers/ToastProvider";
import { ThemeProvider } from "@/components/them-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Admin Dashboard",
    description: "Generated by Admin Dashboard",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>

                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        <ToastProvider />
                        <ModalProvider />
                        {children}
                    </ThemeProvider>

                </body>
            </html>
        </ClerkProvider>
    );
}
